# -*- coding: utf-8 -*-
"""Credit Card using Pycaret

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lKDalC8C9dqgDI_oPhv5zmrgeckZJfl
"""

pip install pycaret

from pycaret.classification import *

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import scipy
from sklearn.metrics import classification_report,accuracy_score

df= pd.read_csv("/content/drive/MyDrive/creditcard.csv")

df.head()

from pycaret.classification import *

model= setup(data= df, target= 'Class')

compare_models()

random_forest= create_model('rf')

random_forest

tuned_model= tune_model('random_forest')

pred_holdout = predict_model(random_forest,data= x_test)

pred_holdout
